name: Build tvOS App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: List Xcode Projects and Schemes
      run: |
        echo "=== Project Structure ==="
        ls -la
        echo "=== Xcode Projects ==="
        find . -name "*.xcodeproj" -type d
        echo "=== Available Schemes ==="
        xcodebuild -project StreamingApp.xcodeproj -list
    
    - name: Build for tvOS Simulator
      run: |
        xcodebuild -project StreamingApp.xcodeproj \
                   -scheme StreamingApp \
                   -destination 'platform=tvOS Simulator,name=Apple TV' \
                   -configuration Debug \
                   clean build
    
    - name: Run Tests (if available)
      run: |
        xcodebuild -project StreamingApp.xcodeproj \
                   -scheme StreamingApp \
                   -destination 'platform=tvOS Simulator,name=Apple TV' \
                   test || echo "No tests found or test failed - continuing"
    
    - name: Build Status
      run: echo "✅ tvOS app built successfully for simulator testing"
