name: Build tvOS App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: List Available Simulators
      run: |
        echo "=== Available tvOS Simulators ==="
        xcrun simctl list devices tvOS
        echo "=== Available Destinations ==="
        xcodebuild -project StreamingApp.xcodeproj -scheme StreamingApp -showdestinations
    
    - name: Build for tvOS
      run: |
        xcodebuild -project StreamingApp.xcodeproj \
                   -scheme StreamingApp \
                   -sdk appletvsimulator \
                   -configuration Debug \
                   clean build
    
    - name: Build Status
      run: echo "✅ tvOS app built successfully"
